### ISSUE TITLE
Example code does not work

### ISSUE THREAD

**Issue by doccosmos** [trishullab/LibraryAugmentedSymbolicRegression.jl#21]
Using Julia 1.10.5 and installing LibraryAugmentedSymbolicRegression via the Julia package manager,
the example code produces:

model = LaSRRegressor(
    niterations=50,
    binary_operators=[+, -, *],
    unary_operators=[cos],
    llm_options=LLMOptions(
        active=true,
        weights=LLMWeights(llm_mutate=0.1, llm_crossover=0.1, llm_gen_random=0.1),
        promtp_evol=true,
        prompt_concepts=true,
        api_key="token-abc123",
        model="meta-llama/Meta-Llama-3-8B-Instruct",
        api_kwargs=Dict("url" => "http://localhost:11434/v1"),
        var_order=Dict("a" => "angle", "b" => "bias")
    )
)

MethodError: no method matching LLMOptions(; active::Bool, weights::LLMWeights, promtp_evol::Bool, prompt_concepts::Bool, api_key::String, model::String, api_kwargs::Dict{String, String}, var_order::Dict{String, String})

Closest candidates are:
  LLMOptions(::Bool, ::LLMWeights, ::Int64, ::Bool, ::Bool, ::String, ::String, ::Dict, ::Dict, ::String, ::String, ::AbstractString, ::Union{Nothing, Dict}, ::UInt32, ::Bool) got unsupported keyword arguments "active", "weights", "promtp_evol", "prompt_concepts", "api_key", "model", "api_kwargs", "var_order"
   @ LibraryAugmentedSymbolicRegression ~/.julia/packages/LibraryAugmentedSymbolicRegression/Ncf4t/src/LLMOptions.jl:52
  LLMOptions(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any) got unsupported keyword arguments "active", "weights", "promtp_evol", "prompt_concepts", "api_key", "model", "api_kwargs", "var_order"
   @ LibraryAugmentedSymbolicRegression ~/.julia/packages/LibraryAugmentedSymbolicRegression/Ncf4t/src/LLMOptions.jl:52
  LLMOptions(; active, weights, num_pareto_context, prompt_concepts, prompt_evol, api_key, model, api_kwargs, http_kwargs, llm_recorder_dir, prompts_dir, llm_context, var_order, idea_threshold, is_parametric) got unsupported keyword argument "promtp_evol"
   @ LibraryAugmentedSymbolicRegression ~/.julia/packages/LibraryAugmentedSymbolicRegression/Ncf4t/src/LLMOptions.jl:51

Stacktrace:
 [1] kwerr(kw::@NamedTuple{active::Bool, weights::LLMWeights, promtp_evol::Bool, prompt_concepts::Bool, api_key::String, model::String, api_kwargs::Dict{String, String}, var_order::Dict{String, String}}, args::Type)
   @ Base ./error.jl:165
 [2] top-level scope
   @ In[12]:1

**Comment by atharvas** [comment]
Hi! Thanks for testing this out! Let me debug this and get back to you.

**Comment by atharvas** [comment]
Fixed! I also added a section at the end that gives instructions on how to set up a simple LLM server to run the full pipeline!
